language: cpp
sudo: required
os: osx
compiler: gcc
osx_image: xcode10.1
before_install:
  - QT_VERSION_MM=56
  - QT_VERSION_FULL=562-trusty
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-add-repository --yes ppa:beineri/opt-qt$QT_VERSION_FULL
      && sudo apt-get update -qq
      && sudo apt-get install -qq qt${QT_VERSION_MM}base qt${QT_VERSION_MM}tools
      && export CMAKE_PREFIX_PATH=/opt/qt${QT_VERSION_MM};
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew outdated cmake || brew upgrade cmake;
      brew install qt5;
      export CMAKE_PREFIX_PATH=$(brew --prefix qt5);
    fi
 
before_script:
   - mkdir build
   - cd build
   - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG -DDISABLE_MAINTAINER_CFLAGS=off

script: 
  - make
  
  notifications:
  email:
    recipients:
      - kirilenko_aa@mail.ru
